fix: Fix add_component() type error with Mypy
When calling `pipeline.add_component()` with any component instance,
Mypy complains:

```
error: Argument 2 to "add_component" of "PipelineBase" has incompatible type "X"; expected "Component"  [arg-type]
note: Protocol member Component.run expected settable variable, got read-only attribute
```

The issue is that `run` of the `Component` protocol is currently
defined as a mutable attribute (`run: ...`). Use `@property` instead
to only require a getter.